export const GENRES = [
  { label: "Action", url: "/genre/action" },
  { label: "Adventure", url: "/genre/adventure" },
  { label: "Animation", url: "/genre/animation" },
  { label: "Comedy", url: "/genre/comedy" },
  { label: "Crime", url: "/genre/crime" },
  { label: "Documentary", url: "/genre/documentary" },
  { label: "Drama", url: "/genre/drama" },
  { label: "Family", url: "/genre/family" },
  { label: "Fantasy", url: "/genre/fantasy" },
  { label: "History", url: "/genre/history" },
  { label: "Horror", url: "/genre/horror" },
  { label: "Kids", url: "/genre/kids" },
  { label: "Music", url: "/genre/music" },
  { label: "Mystery", url: "/genre/mystery" },
  { label: "News", url: "/genre/news" },
  { label: "Reality", url: "/genre/reality" },
  { label: "Romance", url: "/genre/romance" },
  { label: "Science Fiction", url: "/genre/science-fiction" },
  { label: "Soap", url: "/genre/soap" },
  { label: "Talk", url: "/genre/talk" },
  { label: "Thriller", url: "/genre/thriller" },
  { label: "War", url: "/genre/war" },
  { label: "War & Politics", url: "/genre/war-politics" },
  { label: "Western", url: "/genre/western" },
]

export const COUNTRIES = [
  { label: "Argentina", url: "/country/argentina" },
  { label: "Australia", url: "/country/australia" },
  { label: "Belgium", url: "/country/belgium" },
  { label: "Brazil", url: "/country/brazil" },
  { label: "Bulgaria", url: "/country/bulgaria" },
  { label: "Canada", url: "/country/canada" },
  { label: "China", url: "/country/china" },
  { label: "Colombia", url: "/country/colombia" },
  { label: "Denmark", url: "/country/denmark" },
  { label: "Finland", url: "/country/finland" },
  { label: "France", url: "/country/france" },
  { label: "Germany", url: "/country/germany" },
  { label: "India", url: "/country/india" },
  { label: "Indonesia", url: "/country/indonesia" },
  { label: "Ireland", url: "/country/ireland" },
  { label: "Italy", url: "/country/italy" },
  { label: "Japan", url: "/country/japan" },
  { label: "Luxembourg", url: "/country/luxembourg" },
  { label: "Mexico", url: "/country/mexico" },
  { label: "Netherlands", url: "/country/netherlands" },
  { label: "Peru", url: "/country/peru" },
  { label: "Philippines", url: "/country/philippines" },
  { label: "Portugal", url: "/country/portugal" },
  { label: "Russia", url: "/country/russia" },
  { label: "South Africa", url: "/country/south-africa" },
  { label: "South Korea", url: "/country/south-korea" },
  { label: "Spain", url: "/country/spain" },
  { label: "Sweden", url: "/country/sweden" },
  { label: "Taiwan", url: "/country/taiwan" },
  { label: "Thailand", url: "/country/thailand" },
  { label: "UK", url: "/country/uk" },
  { label: "USA", url: "/country/usa" },
]

export const YEARS = Array.from({ length: 30 }, (_, i) => {
  const year = new Date().getFullYear() - i
  return { label: year.toString(), url: `/year/${year}` }
})
